### PR TITLE
H02-Group27

### PR DESCRIPTION
**Pull request by FFS-M**
Assignment2:
- ontology/ontology-example.ttl : Example instance of the ontology.ttl in turtle format.
- ontology/ontology.ttl : Implemented ontology in turtle format
- ./analysis.html: Dataset analysis, URI strategy, License for the data to be generated and published
- ./selfAssessmentHandsOn2: Check list for the assignment2.

### CODE REVIEW

**Comment by rgcmme** [comment]
OK

**Comment by rgcmme** [comment]
The pull request has conflicts in a file. Solve them so it can be merged.

**Comment by FFS-M** [comment]
@rgcmme conflict resolved 🕺🏼

**Comment by rgcmme** [comment]
OK

**Pull request merged**
